### PR TITLE
Contribute Repository Service for TUF

### PR DESCRIPTION
**Pull request by kairoaraujo**
This adds the Repository Service for TUF to the project lifecycle documents in the sandbox stage.

Repository Service for TUF is contributed to the OpenSSF by VMware. Contribution is sponsered by wg-securing-software-repos

Co-authored-by: Kairo de Araujo <kdearaujo@vmware.com>
Signed-off-by: Joshua Lock <jlock@vmware.com>

### CODE REVIEW

**Comment by joshuagl** [comment]
Tagging @znewman01 to confirm sponsorship by wg-securing-software-repos

**Comment by znewman01** [comment]
Confirming that at the [Jan 12, 2023 meeting](https://docs.google.com/document/d/1-f6m442MHg9hktrbcp-4sM9GbZC3HLTpZPpxMXjMCp4/edit) of wg-securing-software-repos (of which I was the acting chair) we reached consensus on sponsoring this project.

**Comment by SecurityCRob** [comment]
Curious here... this is already a CNCF project.  Is the intention to remove it there and move to OSSF?

https://theupdateframework.io/

**Comment by joshuagl** [comment]
Good question @SecurityCRob. I will try and answer concisely, please let me know where the answer falls short.

The Update Framework (TUF) is a CNCF project that consists of a [specification](https://theupdateframework.github.io/specification/latest/) and several implementations (libraries — we have [Python](https://github.com/theupdateframework/python-tuf), [Go](https://github.com/theupdateframework/go-tuf), [Rust](https://github.com/theupdateframework/rust-tuf), and [JavaScript](https://github.com/theupdateframework/tuf-js)). TUF adoptions are implementations of a TUF-conformant repository design and client configuration (i.e., Sigstore's [root-signing](https://github.com/sigstore/root-signing) as repository and [cosign](https://github.com/sigstore/cosign) as client configured for that repository). Typically a TUF adoption is an application built using an implementation (Sigstore uses go-tuf), but it could equally choose to implement the spec as part of the app rather than relying on a library.

Repository Service for TUF (RSTUF) is the repository side of a TUF adoption. It aims to make it easier for repositories to adopt TUF. Adopters don't have to be a TUF expert and design the repository integration. The integration is also simpler because it's abstracted behind higher-level RSTUF API calls, rather than having to author a larger (and often more invasive) change to implement the repository.

The initial version of RSTUF implements [PEP 458](https://peps.python.org/pep-0458/), which is an initial TUF repository design for PyPI. In future we plan to extend RSTUF to cover additional repository designs.

The TUF specification and several implementations are CNCF projects. RSTUF, as a TUF adoption/application, isn't part of the TUF project.

**Comment by AevaOnline** [comment]
The project does not appear to currently meet the [entry requirements ](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#sandbox-entry-requirements-and-considerations) for the Sandbox stage, as it only lists maintainers from VMWare.

> Sandbox Entry Requirements and Considerations
> Projects must have a minimum of two maintainers with different organization affiliations.

**Comment by SecurityCRob** [comment]
> Good question @SecurityCRob. I will try and answer concisely, please let me know where the answer falls short.
> 
> The Update Framework (TUF) is a CNCF project that consists of a [specification](https://theupdateframework.github.io/specification/latest/) and several implementations (libraries — we have [Python](https://github.com/theupdateframework/python-tuf), [Go](https://github.com/theupdateframework/go-tuf), [Rust](https://github.com/theupdateframework/rust-tuf), and [JavaScript](https://github.com/theupdateframework/tuf-js)). TUF adoptions are implementations of a TUF-conformant repository design and client configuration (i.e., Sigstore's [root-signing](https://github.com/sigstore/root-signing) as repository and [cosign](https://github.com/sigstore/cosign) as client configured for that repository). Typically a TUF adoption is an application built using an implementation (Sigstore uses go-tuf), but it could equally choose to implement the spec as part of the app rather than relying on a library.
> 
> Repository Service for TUF (RSTUF) is the repository side of a TUF adoption. It aims to make it easier for repositories to adopt TUF. Adopters don't have to be a TUF expert and design the repository integration. The integration is also simpler because it's abstracted behind higher-level RSTUF API calls, rather than having to author a larger (and often more invasive) change to implement the repository.
> 
> The initial version of RSTUF implements [PEP 458](https://peps.python.org/pep-0458/), which is an initial TUF repository design for PyPI. In future we plan to extend RSTUF to cover additional repository designs.
> 
> The TUF specification and several implementations are CNCF projects. RSTUF, as a TUF adoption/application, isn't part of the TUF project.

Thanks for the reply Joshua.  I know we're all friends and family (OSSF-CNCF), but do you foresee any risks or challenges in housing the separate components in the different foundations?  Why is RSTUF petitioning here and not back where there is already an established relationship & community?

**Comment by joshuagl** [comment]
> The project does not appear to currently meet the [entry requirements ](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#sandbox-entry-requirements-and-considerations) for the Sandbox stage, as it only lists maintainers from VMWare.

This PR lists maintainers from three different organisations (VMware, NYU, and Channable), while the [MAINTAINERS.rst](https://github.com/vmware/repository-service-tuf/blob/8cbf1390e1099b2183c3ee59ee61e4dd3ad41f65/MAINTAINERS.rst) lists only maintainers from VMware. The project is composed of several repositories which are combined for easier management through the umbrella repository. @kairoaraujo I think we should update the umbrella repository to list all maintainers, given that each component maintainer contributes to the overall project maintenance. WDYT?

**Comment by joshuagl** [comment]
> Thanks for the reply Joshua. I know we're all friends and family (OSSF-CNCF), but do you foresee any risks or challenges in housing the separate components in the different foundations? Why is RSTUF petitioning here and not back where there is already an established relationship & community?

Full disclosure, I am deeply invested in both foundations as a maintainer on TUF and in-toto projects in CNCF and maintainer on SLSA projects in OpenSSF.

Personally, I do not anticipate risks or challenges related to this contribution. The OpenSSF has a different, potentially broader, audience than the CNCF. Many of the folks we hope will adopt RSTUF are members of the OpenSSF and participating in wg-securing-software-repos. 

From an engineering perspective, treating TUF as an implementation detail enables RSTUF to focus on providing the best experience for users. RSTUF is starting out as a vehicle for TUF adoption but is explicitly not restricted to being _only_ a TUF application. I also spoke with several members of the TUF contributor community before we proposed RSTUF to the OpenSSF to ensure that it would not be seen in a negative light by collaborators on TUF.

**Comment by kairoaraujo** [comment]
> > The project does not appear to currently meet the [entry requirements ](https://github.com/ossf/tac/blob/main/process/project-lifecycle.md#sandbox-entry-requirements-and-considerations) for the Sandbox stage, as it only lists maintainers from VMWare.
> 
> This PR lists maintainers from three different organisations (VMware, NYU, and Channable), while the [MAINTAINERS.rst](https://github.com/vmware/repository-service-tuf/blob/8cbf1390e1099b2183c3ee59ee61e4dd3ad41f65/MAINTAINERS.rst) lists only maintainers from VMware. The project is composed of several repositories which are combined for easier management through the umbrella repository. @kairoaraujo I think we should update the umbrella repository to list all maintainers, given that each component maintainer contributes to the overall project maintenance. WDYT?

That is correct. The umbrella should list all the maintainers across components. 
I've added a [PR](https://github.com/vmware/repository-service-tuf/pull/264) updating it.

**Comment by kairoaraujo** [comment]
RSTUF maintainers are updated in the umbrella/project repository [MAINTAINERS.rst](https://github.com/vmware/repository-service-tuf/blob/main/MAINTAINERS.rst).

**Comment by AevaOnline** [comment]
> RSTUF maintainers are updated in the umbrella/project repository [MAINTAINERS.rst](https://github.com/vmware/repository-service-tuf/blob/main/MAINTAINERS.rst).

Thanks for clearing that up! 👍

**Comment by david-a-wheeler** [comment]
> Personally, I do not anticipate risks or challenges related to this contribution. The OpenSSF has a different, potentially broader, audience than the CNCF. Many of the folks we hope will adopt RSTUF are members of the OpenSSF and participating in wg-securing-software-repos.

Excellent! Thanks for clearing that up.

**Comment by SecurityCRob** [comment]
> > Thanks for the reply Joshua. I know we're all friends and family (OSSF-CNCF), but do you foresee any risks or challenges in housing the separate components in the different foundations? Why is RSTUF petitioning here and not back where there is already an established relationship & community?
> 
> Full disclosure, I am deeply invested in both foundations as a maintainer on TUF and in-toto projects in CNCF and maintainer on SLSA projects in OpenSSF.
> 
> Personally, I do not anticipate risks or challenges related to this contribution. The OpenSSF has a different, potentially broader, audience than the CNCF. Many of the folks we hope will adopt RSTUF are members of the OpenSSF and participating in wg-securing-software-repos.
> 
> From an engineering perspective, treating TUF as an implementation detail enables RSTUF to focus on providing the best experience for users. RSTUF is starting out as a vehicle for TUF adoption but is explicitly not restricted to being _only_ a TUF application. I also spoke with several members of the TUF contributor community before we proposed RSTUF to the OpenSSF to ensure that it would not be seen in a negative light by collaborators on TUF.

Excellent.  Thanks for the fast replies!

**Comment by dlorenc** [comment]
Thanks all! I'm in support of this.

**Comment by SecurityCRob** [comment]
I also support this

**Comment by bobcallaway** [comment]
I am supportive of this - TUF is already being explored across various ecosystems and efforts to improve its usability are very welcome.

**Comment by inferno-chromium** [comment]
I am supportive of this!

**Review by bobcallaway — APPROVED** [review]

**Review by dlorenc — APPROVED** [review]

**Comment by bobcallaway** [comment]
Per discussion at the March 7, 2023 TAC meeting ([notes](https://docs.google.com/document/d/18BJlokTeG5e5ARD1VFDl5bIP75OFPCtzf77lfadQ4f0/edit#)) this was approved by a vote of 6 in favor, 1 abstain.

**Pull request merged**
