### PR TITLE
Add Q3 2024 DEI WG update

### PR DESCRIPTION
**Pull request by marcelamelara**
Ahead of our Q3 TAC update, we've documented our latest and planned activities.

CC @camaleon2016 @Cyber-JiuJiteria

### CODE REVIEW

**Review by camaleon2016 — APPROVED** [review]
This is solid! Thank you for putting this together.

**Review by SecurityCRob — APPROVED** [review]
Thanks for the DEI update!  Great work, let's brainstorm on how we can get the word out about this group.

**Review by lehors — APPROVED** [review]
LGTM. Thanks!

**Review by steiza — APPROVED** [review]

**Review by sevansdell — APPROVED** [review]
Great update. Thank you!

**Comment by Cyber-JiuJiteria** [comment]
Thanks for the write up! LGTM

**Pull request merged**
