### PR TITLE
Add infrastructure for TI reports to be submitted via github PR

### PR DESCRIPTION
**Pull request by lehors**
This PR proposes a solution to issue #326 to submit TI reports via PRs rather than as issues. It is also entirely github based (no dependency on Google doc) although this could be combined if desired.

### CODE REVIEW

**Comment by mlieberman85** [comment]
Would this summary be in addition to the quarterly presentation?

**Review by SecurityCRob — APPROVED** [review]
+1

**Comment by lehors** [comment]
> Would this summary be in addition to the quarterly presentation?

My proposal is to merely use the report on GitHub. I structured the template based on the presentation that CRob established so it should be an easy transition. I don't personally need the info to be formatted as slides but if people prefer the slide format we could give the option.

**Review by marcelamelara — APPROVED** [review]
LGTM, thanks!

**Comment by marcelamelara** [comment]
Since this is a Content PR, we might want to add a CHANGELOG file in this PR to start following the [TAC decision process](https://github.com/ossf/tac/blob/main/process/TAC-Decision-Process.md#pull-request-types)?

**Comment by SecurityCRob** [comment]
> > Since this is a Content PR, we might want to add a CHANGELOG file in this PR to start following the [TAC decision process](https://github.com/ossf/tac/blob/main/process/TAC-Decision-Process.md#pull-request-types)?
> 
> Sounds good to me. @SecurityCRob do you have a specific format in mind for the CHANGELOG? Are we making it CHANGELOG.md?

CHANGELOG.md would be great!

**Review by marcelamelara — APPROVED** [review]
LGTM thanks!

**Pull request merged**
