### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by Danajoyluck**
added entries for adding security baseline requirements to project-lifecycle.md

### CODE REVIEW

**Review by marcelamelara — COMMENTED** [review]
Thanks @Danajoyluck ! Could you please also add an entry for the sandbox changes?

**Comment by Danajoyluck** [comment]
Thank you @marcelamelara .... I added the entry for #355.

**Review by SecurityCRob — APPROVED** [review]
please bundle update to changelog along with requested change in the future into one PR

**Review by steiza — APPROVED** [review]

**Comment by Danajoyluck** [comment]
Thank you @SecurityCRob and @steiza

**Pull request merged**
