### PR TITLE
Create s2c2f_incubation_stage.md

### PR DESCRIPTION
**Pull request by adriandiglio**
This is the application for S2C2F to be at the Incubation Stage of the Project lifecycle within the OpenSSF.

### CODE REVIEW

**Comment by adriandiglio** [comment]
Our README file points to these meeting notes (link below), which have notes from Aug 2022 all the way through present. It's the only meeting notes doc that we've ever had, and we've been capturing meeting notes for every bi-weekly sync. I'm not sure what link you clicked on? 

https://docs.google.com/document/d/10Q_VOvKsGaYJoK-5yJY4868mTkYZjEo-6xV6ghYS84k/edit?usp=sharing

**Comment by adriandiglio** [comment]
@SecurityCRob could you please check this again? We did delete the link to the "empty" meeting minutes doc.

**Review by SecurityCRob — APPROVED** [review]
Thanks for getting the notes linked Adrian.  LGTM

**Comment by adriandiglio** [comment]
@lehors Thank you for the comment, and my apologies for the delay. This PR now includes another commit where I made an update to the README to update S2C2F as being in the Incubating phase, and includes a link to the new .md that this PR is creating.

**Review by lehors — APPROVED** [review]
Thanks! LGTM.

**Comment by adriandiglio** [comment]
Thanks @lehors and @SecurityCRob! Can either of you please merge the PR? I don't have write access, so I'm unable to merge.

**Review by marcelamelara — CHANGES_REQUESTED** [review]
Thanks @adriandiglio ! Excited to add S2C2F as an incubating project!

**Comment by adriandiglio** [comment]
@marcelamelara thanks for the comment! We already had a link to the Contributing Guide, but I went ahead and added a link to the Meeting Notes. I hope this means this PR can be merged :)

**Comment by lehors** [comment]
This kind of PR requires approval from a majority of the TAC members to be merged.

**Review by camaleon2016 — APPROVED** [review]

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Comment by bobcallaway** [comment]
LGTM, but some feedback for S2C2F to consider: I'd recommend that there a conscious effort to improve both the diversity of the contributions (beyond predominantly MSFT employees), as well as working on smaller PRs so the evidence on contribution of to the document itself is present in GitHub vs just evidence in meeting notes/Slack channels. Working on a specification is different than writing code, but the mechanisms used are important to being inclusive to new contributors, who may be in different timezones or who are otherwise unable to attend face-to-face meetings.

**Pull request merged**
