### PR TITLE
Propose Securing Critical Project WG to Incubating

### PR DESCRIPTION
**Pull request by jeffmendoza**
Following the [submission process](https://github.com/ossf/tac/blob/main/process/working-group-lifecycle.md#submission-process) and using the [template](https://github.com/ossf/tac/blob/main/process/templates/WG_NAME_incubating_stage.md). Please point out anything missing. Thanks!

### CODE REVIEW

**Review by SecurityCRob — COMMENTED** [review]
under Governance, I don't see any listing of members in the git repo either in the readme, a members or contributors file.  Can we get that added please?

**Review by steiza — APPROVED** [review]
LGTM - thanks!

**Review by sevansdell — APPROVED** [review]
lgtm

**Review by bobcallaway — APPROVED** [review]

**Review by lehors — APPROVED** [review]

**Review by SecurityCRob — APPROVED** [review]
+1

**Comment by SecurityCRob** [comment]
Congrats SCI WG!  You are now Incubating!!

**Pull request merged**
