### PR TITLE
Extend election dates

### PR DESCRIPTION
**Pull request by riaankleinhans**
Extend election dates to allow more time for nomination and voter registeration

### CODE REVIEW

**Review by lehors — APPROVED** [review]
LGTM

**Review by marcelamelara — APPROVED** [review]
Thanks so much @riaankleinhans ! LGTM.

**Review by mlieberman85 — APPROVED** [review]
LGTM

**Review by bobcallaway — APPROVED** [review]

**Review by sevansdell — COMMENTED** [review]
looks good!

**Pull request merged**
