### PR TITLE
protobom - OpenSSF Sandbox Application

### PR DESCRIPTION
**Pull request by puerco**
The protobom project is seeking admission to the OpenSSF sandbox. We aim to become part of the Security Tooling WG where we presented the project at the Dec 11th, 2023 meeting.

/cc @ware 

## Overview

protobom is a [protocol buffers](https://protobuf.dev/getting-started/) representation of SBOM data able to ingest documents in modern [SPDX](https://spdx.dev/) and [CycloneDX](https://cyclonedx.org/) versions without loss. It has an accompanying Go library generated from the protocol buffers definiton that implements ingesters and renderers for those formats as well as graph data manipulation primitives. 

### List of project maintainers

The project has 9 maintainers from 6 different organizations:

*  Ori Avraham, Manifest, @manifestori
*  Daniel Bardenstein, Manifest, @bardenstein 
*  Adolfo García Veytia, Chainguard, @puerco
*  Xunchao Hu, Deepbits, @smarabbit
*  Frederick Kautz, TestifySec, @fkautz
*  John Speed Meyers, Chainguard, @jspeed-meyers
*  Danny Nebenzahl, Scribe, @dn-scribe
*  Jonathan Ness, Veramine, @veramine
*  Mikhail Swift, TestifySec, @mikhailswift

### Mission of the project

The project must be aligned with the OpenSSF mission and either be a novel approach for existing areas, address an unfulfilled need, or be initial code needed for OpenSSF WG work. It is preferred that extensions of existing OpenSSF projects collaborate with the existing project rather than seek a new project.

> The protobom project strives to become a foundational library and associated
> command line tools to create, read, modify, and write Software Bill of
> Materials (SBOM) data. The project values the richness and innovation of the
> leading SBOM formats and aims to build a common set of abstractions on top of
> them to enable projects to easily add SBOM capabilities without worrying
> about the details of parsing or rendering.

#### Specific Goals Include:

* Building an I/O layer for Software Bill of Materials data with support for the
major SBOM formats (CycloneDX/SPDX) in their most common versions and encodings.
* Lossless ingestion of SBOM information.
* Ensuring a predictable and documented degradation path in case of fidelity loss
when writing SBOMs.
* Exposing data querying and manipulation primitives to let users access the
SBOM data efficiently.

#### Non-Goals Include:

* Handling other capabilities of the formats outside of the "bill of materials"
use case. This means that features like vulnerabilities, provenance, VEX, etc
are out of the scope of the protobom project.
* Defining a new SBOM format.

### OpenSSF Mission Alignment

We believe our mission aligns with the OpenSSF mission in the following ways:

> make it easier to sustainably secure the development, maintenance, and
> consumption of the open source software

The protobom project aims to cancel the complexity of reading and writing SBOM
data. It also makes it easier to secure the consumption of open source software
by providing prebuilt abstractions that make it easier to create applications
that verify it.

> fostering collaboration

The library was developed by a cohort of independent companies working together
to solve common SBOM problems under the auspices of the 
[Department of Homeland Security Science and Technology Directorate](https://www.dhs.gov/science-and-technology).

> establishing best practices

Protobom is strongly tested and ensures SBOM data consistency across formats.
Uniform data makes it simpler to establish a quality baseline and check
requirements independently of their origin.

### Security Tooling WG Alignment

The project maintainers believe the project aligns with the Security Tooling WG's
objective to Improve and Develop tools:

> Improve - Some tools need just a little bit of help to offer the best solution.
> We need to, where possible, contribute to improve those tools.
> 
> Develop - Despite the large number of tools available, there are still large
> areas of the security problem space that do not have tools to help developers
> find issues. We will develop those tools where there is interest and bandwidth.

As an independent library, protobom reduces the complexity to improve any tool
that reads, writes or manipulates software bills of materials. By offloading 
the document read and write operations to protobom, SBOM tooling can focus on
its core functionality. 

### IP policy and licensing due diligence

When contributing an existing Project to the OpenSSF, the contribution must
undergo license and IP due diligence by the Linux Foundation (LF).

* Yes __(License due diligence TBD)__
  
### Project References

The project should provide a list of existing resources with links to the repository, and if available, website, a roadmap, contributing guide, demos and walkthroughs, and any other material to showcase the existing breadth, maturity, and direction of the project.

| Reference          | URL |
|--------------------|-----|
| Main Repository    | http://github.com/bom-squad/protobom |
| Contributing guide | https://github.com/bom-squad/protobom/blob/main/CONTRIBUTING.md |
| Roadmap            | https://github.com/bom-squad/protobom/milestone/1 |
| Demos              | **Introduction to Protobom** <br>  https://www.youtube.com/watch?v=Q8XkMVORorI <br> **OpenSSF Security Tooling WG Presentation** <br> (waiting for the recording) |
| Other              |  **Blog Posts** <br> [Working with government and industry to put open source security tooling into practice](https://www.chainguard.dev/unchained/working-with-government-and-industry-to-put-open-source-security-tooling-into-practice) <br> [Can Protobom end the SBOM format wars?](https://www.chainguard.dev/unchained/can-protobom-end-the-sbom-format-wars)   |

### CODE REVIEW

**Comment by jkjell** [comment]
This would be a great addition to OpenSSF. We've already looked at using protobom in an initial [prototype](https://github.com/SBOMit/protobomit) for SBOMit.

**Comment by SecurityCRob** [comment]
I'll set this up as one of the 1st tasks to review for the 2024 TAC.  Will someone from the project and the Tooling WG be able to attend the 0Jan2024 call to present this for the TAC to review please?

**Comment by puerco** [comment]
I can be there on behalf of the project. Hopefully, some of my colleagues can make it too!

**Comment by jeffcshapiro** [comment]
LICENSE INTAKE SCAN & ANALYSIS:  OpenSSF: Protobom
DISTRIBUTION:  Amanda Martin, https://github.com/ossf/tac/pull/238

- This intake scan is a static analysis of the source code in your repository.  A dependency scan was not performed.  Once a project is added to LFX [https://security.lfx.linuxfoundation.org], you can use SNYK to view a dependency scan for both licenses and vulnerabilities.

CODE SCANNED:  [pulled 03–Jan-2024]
- https://github.com/bom-squad/protobom

PROJECT LICENSE:  Apache-2.0
- Top level project license file found.

SPDX LICENSE IDENTIFIERS:  SPDX license identifiers were found in some source file headers.
- I recommend that SPDX license identifiers be added to ALL source file headers.  [see https://spdx.dev/learn/handling-license-info for examples]

PERMISSIVE LICENSES:  Apache-2.0, CC0-1.0, MIT, BSD-3-Clause, Zlib, Python, Artistic-1.0

COPYLEFT LICENSES:  GPL-3.0, GPL-2.0, LGPL-2.1, MPL
- NOTE:  These licenses were detected in SPDX/JSON files which are assumed to be sample or test files, and the licenses do not apply to any actual code - therefore no license conflicts were found.

PROPRIETARY LICENSES:  None found

LICENSE CONFLICTS:  None found

BINARY / PACKAGE FILES:  None found

THIRD PARTY CODE / DEPENDENCIES:  Dependencies were found in the files below.  These dependencies were not scanned, and any potential license conflicts from them are not identified here.
- https://github.com/bom-squad/protobom/blob/main/go.mod
- https://github.com/bom-squad/protobom/blob/main/go.sum

THIRD PARTY NOTICE FILE:  None found

SUMMARY FINDINGS:  The code is licensed under the Apache-2.0 license, which is the project license.  SPDX license identifiers should be added to all source file headers where not already present.  No license conflicts found.

**Comment by SecurityCRob** [comment]
We'll walk through these entry requirements on 9Jan:

Sandbox level Gives/Requirements

1.)  TI must be aligned with the OpenSSF mission and either be a novel approach for existing areas or address an unfulfilled need. It is expected that the initial code needed for an OpenSSF WG to work be kept within their repository and will not function as a project in its own right. Should initial WG code grow and mature that it warrants its own Project status, then it is subject to Sandbox entry requirements. It is preferred that extensions of existing OpenSSF projects collaborate with the existing project rather than seek a new project.
2.)  TI must maintain a diversified contributor base (i.e. not a single-vendor project). TI must have a minimum of two maintainers with different organization affiliations.
3.)  TI must find an aligned WG to host the TI and must have a TAC sponsor that can help guide the TI through processes.
4.)  TI agrees to follow the [Secure Software Development Guiding Principles](https://github.com/ossf/wg-best-practices-os-developers/blob/main/docs/SecureSoftwareGuidingPrinciples.md) and the [Open Source Consumption Manifesto](https://github.com/ossf/wg-endusers/tree/main/MANIFESTO).
5.)  If contributing an existing Project to the OpenSSF, the contribution must undergo license and IP due diligence by the Linux Foundation (LF).
6.)  Provides quarterly updates to the TAC on technical vision and progress on vision.
7.)  TI will have a [SECURITY.md](https://github.com/ossf/project-template/blob/main/SECURITY.md) that describes how the Project manages vulnerabilities, or more broadly how the OSSF handles vulnerability reports

**Comment by mlieberman85** [comment]
I had spoken to @puerco about this and would be down to sponsor.

**Review by lehors — APPROVED** [review]

**Comment by SecurityCRob** [comment]
I'm assuming that @ware from the Tooling WG and @joshbressers from the SBOM Everywhere SIG agree this makes sense?

**Comment by ware** [comment]
100% makes sense.

**Review by torgo — APPROVED** [review]
On review of the info provided, and discussion, it looks good to me. 👍🏻

**Comment by joshbressers** [comment]
The SBOM everywhere group isn't in the tooling business (and doesn't want to be), so I shall default to what @ware says

**Review by SecurityCRob — APPROVED** [review]
I think this is an interesting idea and a great candidate to join us and collaborate

**Review by mlieberman85 — APPROVED** [review]

**Comment by lukehinds** [comment]
congrats protobom devs!

**Pull request merged**
